CREATE DATABASE IF NOT EXISTS TESLA_TELEMETRY;
CREATE SCHEMA IF NOT EXISTS TESLA_TELEMETRY.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS TELEMETRY_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE DATABASE TESLA_TELEMETRY;
USE SCHEMA ANALYTICS;

CREATE STAGE IF NOT EXISTS TELEMETRY_INTERNAL_STAGE
    DIRECTORY = (ENABLE = TRUE);

