USE DATABASE TESLA_TELEMETRY;
USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS RAW_TELEMETRY_EVENTS (
    EVENT_ID STRING NOT NULL,
    VIN STRING NOT NULL,
    VEHICLE_MODEL STRING,
    EVENT_TS TIMESTAMP_TZ,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    SPEED_MPH FLOAT,
    BATTERY_PCT FLOAT,
    ODOMETER_MILES FLOAT,
    POWER_KW FLOAT,
    CHARGING_STATE STRING,
    TIRE_PRESSURE_FL FLOAT,
    TIRE_PRESSURE_FR FLOAT,
    TIRE_PRESSURE_RL FLOAT,
    TIRE_PRESSURE_RR FLOAT,
    OUTSIDE_TEMP_F FLOAT,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS TELEMETRY_ENRICHED (
    EVENT_ID STRING NOT NULL,
    VIN STRING NOT NULL,
    VEHICLE_MODEL STRING,
    EVENT_TS TIMESTAMP_TZ,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    SPEED_MPH FLOAT,
    BATTERY_PCT FLOAT,
    ODOMETER_MILES FLOAT,
    POWER_KW FLOAT,
    CHARGING_STATE STRING,
    TIRE_PRESSURE_FL FLOAT,
    TIRE_PRESSURE_FR FLOAT,
    TIRE_PRESSURE_RL FLOAT,
    TIRE_PRESSURE_RR FLOAT,
    OUTSIDE_TEMP_F FLOAT,
    EVENT_DATE DATE,
    EVENT_HOUR NUMBER,
    IS_MOVING BOOLEAN,
    IS_LOW_BATTERY BOOLEAN,
    AVG_TIRE_PRESSURE FLOAT,
    HAS_TIRE_PRESSURE_ALERT BOOLEAN,
    ENERGY_MODE STRING,
    LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS TELEMETRY_ENRICHED_STAGE LIKE TELEMETRY_ENRICHED;

CREATE TABLE IF NOT EXISTS VEHICLE_HOURLY_METRICS (
    VIN STRING NOT NULL,
    VEHICLE_MODEL STRING,
    EVENT_DATE DATE,
    EVENT_HOUR NUMBER,
    EVENTS NUMBER,
    AVG_SPEED_MPH FLOAT,
    MAX_SPEED_MPH FLOAT,
    AVG_BATTERY_PCT FLOAT,
    MIN_BATTERY_PCT FLOAT,
    MAX_ODOMETER_MILES FLOAT,
    LOW_BATTERY_EVENTS NUMBER,
    TIRE_PRESSURE_ALERTS NUMBER,
    LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS VEHICLE_HOURLY_METRICS_STAGE LIKE VEHICLE_HOURLY_METRICS;

CREATE TABLE IF NOT EXISTS PROCESSED_S3_OBJECTS (
    S3_KEY STRING NOT NULL,
    DAG_RUN_ID STRING,
    PROCESSED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (S3_KEY)
);
