USE DATABASE TESLA_TELEMETRY;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VEHICLE_REAL_TIME_STATUS AS
SELECT
    VIN,
    VEHICLE_MODEL,
    MAX(EVENT_TS) AS LAST_EVENT_TS,
    MAX_BY(BATTERY_PCT, EVENT_TS) AS LAST_BATTERY_PCT,
    MAX_BY(SPEED_MPH, EVENT_TS) AS LAST_SPEED_MPH,
    MAX_BY(CHARGING_STATE, EVENT_TS) AS LAST_CHARGING_STATE,
    MAX_BY(LATITUDE, EVENT_TS) AS LAST_LATITUDE,
    MAX_BY(LONGITUDE, EVENT_TS) AS LAST_LONGITUDE,
    MAX_BY(ODOMETER_MILES, EVENT_TS) AS LAST_ODOMETER_MILES
FROM TELEMETRY_ENRICHED
GROUP BY VIN, VEHICLE_MODEL;

CREATE OR REPLACE VIEW VEHICLE_ALERTS AS
SELECT
    EVENT_ID,
    VIN,
    VEHICLE_MODEL,
    EVENT_TS,
    CASE
        WHEN BATTERY_PCT < 10 THEN 'CRITICAL_BATTERY'
        WHEN BATTERY_PCT < 20 THEN 'LOW_BATTERY'
        WHEN HAS_TIRE_PRESSURE_ALERT THEN 'LOW_TIRE_PRESSURE'
        WHEN SPEED_MPH > 100 THEN 'HIGH_SPEED'
        ELSE 'NORMAL'
    END AS ALERT_TYPE,
    BATTERY_PCT,
    SPEED_MPH,
    AVG_TIRE_PRESSURE
FROM TELEMETRY_ENRICHED
WHERE BATTERY_PCT < 20
   OR HAS_TIRE_PRESSURE_ALERT
   OR SPEED_MPH > 100;

